export type DemoType =
  | "api"        // API連携系
  | "ai"         // AI生成系
  | "analytics"  // 分析・レポート系
  | "settings"   // 管理・設定系
  | "publish"    // 投稿・配信系
  | "monitor"    // 監視・通知系
  | "auth";      // 認証・課金系

export interface FeatureDetail {
  slug: string;
  title: string;
  category: string;
  description: string;
  demoType: DemoType;
  details: string;
  icon: string;
  status: "active" | "coming" | "beta";
  techStack: string[];
}

export const featureDetails: FeatureDetail[] = [
  // ============================================================
  // 口コミ管理 (reviews)
  // ============================================================
  {
    slug: "feature-001",
    title: "AI自動返信",
    category: "口コミ管理",
    description: "口コミに対してAIで返信内容を考え自動返信。NGワード・AIOテンプレ対応。",
    demoType: "ai",
    details: "口コミ内容を自然言語処理で解析し、店舗のトンマナに合った返信文を自動生成します。NGワードフィルタにより不適切な表現を排除し、AIO最適化テンプレートを自動挿入。設定した条件に合致する口コミには全自動で返信を投稿します。",
    icon: "🤖",
    status: "active",
    techStack: ["OpenAI GPT-4", "Google Business Profile API", "NGワードフィルタ"],
  },
  {
    slug: "feature-002",
    title: "半自動返信",
    category: "口コミ管理",
    description: "1つの口コミに対して5つほど返信候補を生成。クリックで返信、編集・再生成も可能。",
    demoType: "ai",
    details: "AIが口コミの内容・トーン・評価を分析し、最適な返信候補を複数パターン生成。スタッフは候補を選択するだけで返信が完了します。必要に応じて手動編集や再生成も可能です。",
    icon: "✋",
    status: "active",
    techStack: ["OpenAI GPT-4", "GBP API", "リアルタイムプレビュー"],
  },
  {
    slug: "feature-003",
    title: "未返信件数お知らせ",
    category: "口コミ管理",
    description: "未返信の口コミが何件あるかパッと見てわかる通知表示。",
    demoType: "monitor",
    details: "ダッシュボード上にリアルタイムで未返信件数を表示。期限超過の口コミは色分けで警告し、優先度の高い口コミから対応できるよう並び替えます。",
    icon: "🔔",
    status: "active",
    techStack: ["GBP API", "WebSocket", "通知システム"],
  },
  {
    slug: "feature-004",
    title: "口コミ評価推移",
    category: "口コミ管理",
    description: "評価の上下をグラフで表示。3.5の重要ラインに赤線表示。",
    demoType: "analytics",
    details: "口コミの平均評価を時系列グラフで可視化。MEOにおいて重要な3.5ラインを基準線として表示し、評価が下回った場合にアラートを発信します。日次・週次・月次で切り替え可能。",
    icon: "📊",
    status: "active",
    techStack: ["Recharts", "GBP API", "データ集計エンジン"],
  },
  {
    slug: "feature-005",
    title: "口コミ増加量推移",
    category: "口コミ管理",
    description: "いつ何件増えたかをグラフ表示。期間で絞り込み可能。",
    demoType: "analytics",
    details: "口コミの増加ペースを日別・週別・月別でグラフ化。施策の効果測定や季節変動の把握に活用できます。期間フィルタで任意の範囲を表示可能。",
    icon: "📈",
    status: "active",
    techStack: ["Recharts", "GBP API", "日次バッチ処理"],
  },
  {
    slug: "feature-006",
    title: "競合店舗の月間口コミ返信率",
    category: "口コミ管理",
    description: "競合の全体口コミに対する返信率を表示。",
    demoType: "analytics",
    details: "設定した競合店舗の口コミ返信率を自動計測し、自店舗との比較を可視化。返信率が低い競合に対する優位性や、改善すべきポイントを明確にします。",
    icon: "🏪",
    status: "active",
    techStack: ["GBP API", "競合分析エンジン", "スクレイピング"],
  },
  {
    slug: "feature-007",
    title: "口コミの内容分析",
    category: "口コミ管理",
    description: "接客・内装・料理・サービス等のカテゴリ別に良い/悪い口コミを分析。",
    demoType: "analytics",
    details: "口コミテキストをNLPで解析し、接客・料理・雰囲気・価格・清潔感などのカテゴリ別にポジティブ/ネガティブを分類。改善優先度を自動算出します。",
    icon: "🔍",
    status: "active",
    techStack: ["自然言語処理", "感情分析AI", "カテゴリ分類モデル"],
  },
  {
    slug: "feature-008",
    title: "アンケートによる口コミ獲得",
    category: "口コミ管理",
    description: "アンケート回答で口コミ文章を生成。★3以下は自社、★4以上はGoogleへ誘導。",
    demoType: "ai",
    details: "お客様がアンケートに回答すると、AIが口コミ文章を自動生成。★4以上の高評価者はGoogleマップの口コミ投稿ページへ誘導し、★3以下は自社フィードバックシステムに蓄積します。",
    icon: "📋",
    status: "active",
    techStack: ["AIテキスト生成", "QRコード生成", "振り分けロジック"],
  },
  {
    slug: "feature-009",
    title: "多言語対応",
    category: "口コミ管理",
    description: "返信文の候補を決定したら口コミと同じ言語に翻訳して返信。",
    demoType: "ai",
    details: "口コミの言語を自動検出し、返信文を同じ言語に翻訳して投稿。英語・中国語・韓国語など主要言語に対応。インバウンド対策として外国語の口コミにも漏れなく対応できます。",
    icon: "🌍",
    status: "active",
    techStack: ["翻訳API", "言語検出", "GBP API"],
  },
  {
    slug: "feature-010",
    title: "LLMO最適なQ&A・返信文作成",
    category: "口コミ管理",
    description: "AIOに適した口コミ返信文テンプレートを自動作成。",
    demoType: "ai",
    details: "AI検索（AIO/LLMO）に最適化された返信文テンプレートを生成。店舗の対策キーワードを自然に含め、AIがソースとして引用しやすい構造化された返信文を作成します。",
    icon: "🤖",
    status: "active",
    techStack: ["LLM最適化エンジン", "キーワード挿入", "構造化テキスト"],
  },
  {
    slug: "feature-011",
    title: "いい口コミキーワードランキング",
    category: "口コミ管理",
    description: "料理・接客等、何で喜ばれているかをランキング表示。",
    demoType: "analytics",
    details: "高評価口コミからポジティブキーワードを抽出し、出現頻度順にランキング化。自店舗の強みを客観的に把握でき、投稿や広告のコピーライティングに活用できます。",
    icon: "🏆",
    status: "active",
    techStack: ["テキストマイニング", "キーワード抽出", "ランキングエンジン"],
  },
  {
    slug: "feature-012",
    title: "口コミハイライト",
    category: "口コミ管理",
    description: "レビューに多く含まれるワードをGOOD/BADで可視化。",
    demoType: "analytics",
    details: "全口コミから頻出ワードを抽出し、ポジティブ/ネガティブに分類してワードクラウド形式で可視化。一目で自店舗の評判の傾向を把握できます。",
    icon: "💬",
    status: "active",
    techStack: ["ワードクラウド", "感情分析", "テキスト解析"],
  },

  // ============================================================
  // 投稿管理 (posts)
  // ============================================================
  {
    slug: "feature-013",
    title: "ヒアリングシートの作成",
    category: "投稿管理",
    description: "選択式でトンマナや基礎情報をヒアリングできるアンケートを作成。他媒体の使用許可も一緒にヒアリング。",
    demoType: "settings",
    details: "店舗の雰囲気・トンマナ・基礎情報を効率的に収集するためのヒアリングシートを自動生成。選択式UIで回答しやすく、収集した情報は口コミ返信・投稿生成・初期整備に自動反映されます。",
    icon: "📋",
    status: "active",
    techStack: ["フォームビルダー", "データベース", "自動反映エンジン"],
  },
  {
    slug: "feature-014",
    title: "ヒアリングシートの取り込み",
    category: "投稿管理",
    description: "ヒアリング結果を口コミ返信・投稿文章・初期整備に自動反映。",
    demoType: "api",
    details: "ヒアリングシートの回答データをパースし、各機能のパラメータとして自動セット。店舗ごとのカスタマイズ情報がシステム全体に即座に反映されます。",
    icon: "📥",
    status: "active",
    techStack: ["データパーサー", "自動反映API", "バリデーション"],
  },
  {
    slug: "feature-015",
    title: "投稿の種類の設定",
    category: "投稿管理",
    description: "1ヶ月分の投稿の種類（通常/特典/イベント等）を先に設定。",
    demoType: "settings",
    details: "月間の投稿計画を投稿種類（通常・特典・イベント・写真・多言語）ごとに事前設定。カレンダービューで視覚的に確認でき、バランスの取れた投稿スケジュールを組めます。",
    icon: "📅",
    status: "active",
    techStack: ["カレンダーUI", "スケジューラ", "投稿タイプ管理"],
  },
  {
    slug: "feature-016",
    title: "AI文章自動生成",
    category: "投稿管理",
    description: "投稿種類＋ヒアリング情報＋AIO/LLMO＋MEO＋Chubby独自ルールを参照した文章を自動生成。",
    demoType: "ai",
    details: "複数のデータソース（ヒアリング情報、対策キーワード、AIO最適化ルール、MEOベストプラクティス、Chubby独自ルール）を組み合わせて、最適な投稿文章をAIが自動生成します。",
    icon: "🤖",
    status: "active",
    techStack: ["GPT-4", "プロンプトエンジニアリング", "ルールエンジン"],
  },
  {
    slug: "feature-017",
    title: "定型文の自動生成",
    category: "投稿管理",
    description: "投稿種類ごとに3〜5つの定型文を自動生成。お客様が選択するだけ。",
    demoType: "ai",
    details: "投稿の種類に応じたテンプレートを複数パターン自動生成。お客様は好みの定型文を選択するだけで投稿が完了。カスタマイズも可能です。",
    icon: "📝",
    status: "active",
    techStack: ["テンプレートエンジン", "AIテキスト生成", "選択式UI"],
  },
  {
    slug: "feature-018",
    title: "予約投稿",
    category: "投稿管理",
    description: "写真と日時を設定したら自動で予約投稿。当日の時間指定にも対応。",
    demoType: "publish",
    details: "投稿内容と写真を設定し、公開日時を指定すると自動で予約投稿されます。当日の時間指定にも対応しており、最適なタイミングでの投稿が可能です。",
    icon: "⏰",
    status: "active",
    techStack: ["GBP API", "ジョブスケジューラ", "Cron"],
  },
  {
    slug: "feature-019",
    title: "当日の予約投稿（時間指定できる）",
    category: "投稿管理",
    description: "投稿作成UIに当日モード追加→時間セレクタで当日の任意時刻を指定",
    demoType: "publish",
    details: "当日中に投稿したい場合、時間セレクタで任意の時刻を指定可能。急な告知やタイムセールの投稿に最適です。",
    icon: "🕐",
    status: "active",
    techStack: ["タイムピッカーUI", "即時スケジューラ", "GBP API"],
  },
  {
    slug: "feature-020",
    title: "直接投稿",
    category: "投稿管理",
    description: "システム上で設定を完了させたらそのまま直接投稿。",
    demoType: "publish",
    details: "プレビューを確認後、ワンクリックでGBPに直接投稿。予約不要で即座に公開されます。",
    icon: "🚀",
    status: "active",
    techStack: ["GBP API", "リアルタイム投稿", "プレビュー"],
  },
  {
    slug: "feature-021",
    title: "投稿種類の選択",
    category: "投稿管理",
    description: "イベント/特典/日本語/多言語投稿を簡単に選択。定型文・ボタン・URL設定。",
    demoType: "settings",
    details: "投稿の種類をワンクリックで切り替え。種類に応じたフォームが表示され、定型文テンプレート、CTAボタン、リンクURLなどを設定できます。",
    icon: "🏷️",
    status: "active",
    techStack: ["動的フォーム", "投稿タイプ管理", "GBP API"],
  },
  {
    slug: "feature-022",
    title: "特典投稿のタイトル設定",
    category: "投稿管理",
    description: "ホットペッパーから選択式で投稿タイトルを設定。",
    demoType: "settings",
    details: "ホットペッパーに掲載中のクーポン・特典情報を取得し、選択式で投稿タイトルに設定。媒体間の情報一貫性を保ちつつ効率的に投稿を作成できます。",
    icon: "🎫",
    status: "active",
    techStack: ["ホットペッパーAPI", "選択式UI", "GBP API"],
  },
  {
    slug: "feature-023",
    title: "最新情報の閲覧数表示",
    category: "投稿管理",
    description: "投稿がどれだけ閲覧されているかを表示。",
    demoType: "analytics",
    details: "各投稿の閲覧数をリアルタイムで取得・表示。パフォーマンスの高い投稿パターンを分析し、今後の投稿戦略に活用できます。",
    icon: "👁️",
    status: "active",
    techStack: ["GBP Performance API", "インサイト取得", "グラフ表示"],
  },
  {
    slug: "feature-024",
    title: "リンククリック数",
    category: "投稿管理",
    description: "通常投稿・特典投稿のボタンクリック数を投稿ごと/月間/トータルで表示。",
    demoType: "analytics",
    details: "投稿に含まれるCTAボタンやリンクのクリック数を、投稿単位・月間・累計で集計表示。コンバージョンに直結する指標として活用できます。",
    icon: "🔗",
    status: "active",
    techStack: ["GBP API", "クリック計測", "集計エンジン"],
  },
  {
    slug: "feature-025",
    title: "投稿文章の翻訳",
    category: "投稿管理",
    description: "確認後に指定言語に翻訳。言語ごとに文字数範囲を指定可能。",
    demoType: "ai",
    details: "投稿文章を任意の言語に翻訳。言語ごとに最適な文字数範囲を設定でき、各言語の特性に合った自然な翻訳文を生成します。",
    icon: "🌍",
    status: "active",
    techStack: ["翻訳API", "文字数制御", "多言語管理"],
  },
  {
    slug: "feature-026",
    title: "誤字脱字修正",
    category: "投稿管理",
    description: "投稿文章の誤字脱字をAIが自動で修正。",
    demoType: "ai",
    details: "AIが投稿文章をスキャンし、誤字脱字・文法ミスを自動検出・修正。修正箇所はハイライト表示され、承認/却下を選択できます。",
    icon: "✏️",
    status: "active",
    techStack: ["校正AI", "差分表示", "プレビュー"],
  },
  {
    slug: "feature-027",
    title: "重複文章の発見",
    category: "投稿管理",
    description: "過去の投稿と重複する文章がある場合、投稿をブロック＆エラー理由表示。",
    demoType: "monitor",
    details: "新規投稿の文章を過去の全投稿と類似度チェック。一定以上の類似度が検出された場合、投稿をブロックし、重複箇所と類似投稿を具体的に表示します。",
    icon: "🔄",
    status: "active",
    techStack: ["テキスト類似度分析", "ベクトル検索", "ブロックロジック"],
  },
  {
    slug: "feature-028",
    title: "重複写真の発見",
    category: "投稿管理",
    description: "過去の投稿と重複する写真がある場合、投稿をブロック＆重複写真を表示。",
    demoType: "monitor",
    details: "画像のハッシュ値比較とAI画像認識を組み合わせて、過去に投稿した写真との重複を検出。重複が見つかった場合は投稿をブロックし、類似写真を並べて表示します。",
    icon: "📷",
    status: "active",
    techStack: ["画像ハッシュ", "AI画像認識", "重複検出"],
  },
  {
    slug: "feature-029",
    title: "使用写真の加工",
    category: "投稿管理",
    description: "明度・彩度をナチュラルかつきれいに自動加工（過度な加工はNG）。",
    demoType: "ai",
    details: "投稿に使用する写真の明度・彩度・コントラストを自動最適化。過度な加工を避け、ナチュラルかつ魅力的な仕上がりを実現します。",
    icon: "🎨",
    status: "active",
    techStack: ["画像処理AI", "自動補正", "プレビュー"],
  },
  {
    slug: "feature-030",
    title: "月初全自動記事生成",
    category: "投稿管理",
    description: "月初に各店舗で15〜30の記事を自動生成。写真と日付を選べばその日に更新。",
    demoType: "ai",
    details: "毎月月初に各店舗の情報をもとに15〜30件の投稿記事を一括自動生成。スタッフは写真を選んで日付を設定するだけで、1ヶ月分の投稿が完了します。",
    icon: "⚡",
    status: "active",
    techStack: ["バッチ処理", "AI記事生成", "一括スケジューラ"],
  },
  {
    slug: "feature-031",
    title: "月初半自動記事生成",
    category: "投稿管理",
    description: "お客様が気に入った記事に日付と写真を選択すればその日に投稿。",
    demoType: "publish",
    details: "AIが生成した複数の記事候補からお客様が気に入ったものを選択。日付と写真を設定するだけで予約投稿が完了する半自動フローです。",
    icon: "✋",
    status: "active",
    techStack: ["AI記事生成", "選択式UI", "予約投稿"],
  },
  {
    slug: "feature-032",
    title: "予約投稿（写真）",
    category: "投稿管理",
    description: "写真を設定して日時指定で自動投稿。任意枚数を一気にアップロード。",
    demoType: "publish",
    details: "複数枚の写真を一括アップロードし、投稿日時を指定して予約。写真のみの投稿にも対応し、GBPのフォトギャラリーを効率的に充実させます。",
    icon: "📸",
    status: "active",
    techStack: ["画像アップロード", "バッチ処理", "GBP Media API"],
  },
  {
    slug: "feature-033",
    title: "直接投稿（写真）",
    category: "投稿管理",
    description: "写真を設定して直接投稿。任意枚数を一気にアップロード。",
    demoType: "publish",
    details: "写真を選択してワンクリックで即座にGBPに投稿。複数枚の同時アップロードに対応し、スピーディーな写真更新が可能です。",
    icon: "📤",
    status: "active",
    techStack: ["GBP Media API", "一括アップロード", "画像最適化"],
  },
  {
    slug: "feature-034",
    title: "投稿エラー時の原因特定",
    category: "投稿管理",
    description: "投稿拒否時に文章を1行ずつ検証→URL追加→写真追加の順で原因特定。",
    demoType: "monitor",
    details: "投稿がGoogleに拒否された場合、文章を1行ずつ段階的に検証し、どの部分が原因かを自動特定。URL・写真の追加順序でも検証を行い、具体的な原因と対処法を提示します。",
    icon: "🔧",
    status: "active",
    techStack: ["段階的検証", "エラー分析", "GBP API"],
  },
  {
    slug: "feature-035",
    title: "店舗別の最適投稿時間帯分析",
    category: "投稿管理",
    description: "インサイトから最もエンゲージメントが高い曜日・時間帯を自動提案。",
    demoType: "analytics",
    details: "過去のインサイトデータを分析し、各店舗で最もエンゲージメントが高い曜日・時間帯を特定。最適な投稿タイミングを自動提案します。",
    icon: "⏱️",
    status: "active",
    techStack: ["GBP Insights API", "統計分析", "レコメンドエンジン"],
  },
  {
    slug: "feature-036",
    title: "季節・イベント自動カレンダー",
    category: "投稿管理",
    description: "祝日・季節イベント・業種別繁忙期を自動反映した投稿カレンダー。",
    demoType: "settings",
    details: "日本の祝日、季節イベント、業種別の繁忙期を自動でカレンダーに反映。イベントに合わせた投稿テーマの提案も行います。",
    icon: "📆",
    status: "active",
    techStack: ["イベントDB", "カレンダーAPI", "業種別テンプレート"],
  },
  {
    slug: "feature-037",
    title: "AI画像生成",
    category: "投稿管理",
    description: "写真がない場合でもAIでイメージ画像を自動生成して投稿に活用。",
    demoType: "ai",
    details: "店舗の情報やテーマに基づいてAIがイメージ画像を自動生成。実写真がない場合でも魅力的なビジュアルで投稿を作成できます。",
    icon: "🎨",
    status: "active",
    techStack: ["DALL-E / Stable Diffusion", "プロンプト最適化", "画像編集"],
  },
  {
    slug: "feature-038",
    title: "ネガティブ口コミ急増アラート",
    category: "投稿管理",
    description: "短期間に低評価口コミが集中した場合、即時通知で炎上リスクを早期検知。",
    demoType: "monitor",
    details: "低評価口コミの増加速度を常時監視。閾値を超えた場合に即時アラートを発信し、炎上リスクの早期検知と迅速な対応を支援します。",
    icon: "🚨",
    status: "active",
    techStack: ["リアルタイム監視", "閾値設定", "通知API"],
  },
  {
    slug: "feature-039",
    title: "口コミからのキーワード自動抽出",
    category: "投稿管理",
    description: "頻出ワードをワードクラウドで可視化し、対策KWや投稿ネタに活用。",
    demoType: "analytics",
    details: "全口コミテキストからキーワードを自動抽出し、ワードクラウドで可視化。投稿のネタ出しやキーワード対策の参考に活用できます。",
    icon: "☁️",
    status: "active",
    techStack: ["形態素解析", "ワードクラウド", "キーワード抽出"],
  },
  {
    slug: "feature-040",
    title: "動画投稿",
    category: "投稿管理",
    description: "最新投稿や写真投稿で動画を予約投稿するシステム。",
    demoType: "publish",
    details: "動画ファイルをアップロードし、GBPの最新情報や写真セクションに予約投稿。動画コンテンツでユーザーの関心を引きます。",
    icon: "🎥",
    status: "active",
    techStack: ["動画アップロード", "GBP Media API", "トランスコーディング"],
  },
  {
    slug: "feature-041",
    title: "一括投稿",
    category: "投稿管理",
    description: "系列で写真や文章を同じもので投稿する際に一括投稿。",
    demoType: "publish",
    details: "系列店舗に対して同じ内容の投稿を一括で配信。店舗ごとにカスタマイズも可能で、チェーン店の運用効率を大幅に向上させます。",
    icon: "📦",
    status: "active",
    techStack: ["一括API呼び出し", "店舗グループ管理", "バッチ処理"],
  },
  {
    slug: "feature-042",
    title: "記事生成一括処理（全店舗）",
    category: "投稿管理",
    description: "全店舗分の記事を一括生成→予約投稿に追加。AI完結が理想。",
    demoType: "ai",
    details: "全管理店舗の記事をAIが一括生成し、各店舗の予約投稿キューに自動追加。人手を介さずAI完結で月間投稿計画を完成させます。",
    icon: "⚡",
    status: "active",
    techStack: ["バッチAI処理", "全店舗ループ", "予約投稿API"],
  },
  {
    slug: "feature-043",
    title: "ヒアリング情報の簡略化",
    category: "投稿管理",
    description: "他ツール連携で入力を自動化し、ヒアリング作業を最小限に簡略化。",
    demoType: "api",
    details: "GBP・食べログ・ホットペッパーなどの既存情報を自動取得し、ヒアリングシートにプリセット。お客様の入力作業を最小限に削減します。",
    icon: "🔧",
    status: "active",
    techStack: ["多媒体API", "データプリセット", "自動入力"],
  },

  // ============================================================
  // リード獲得・分析 (lead)
  // ============================================================
  {
    slug: "feature-044",
    title: "店舗調査",
    category: "リード獲得・分析",
    description: "GoogleマップのリンクまたはGBP名を入力すればMEO強度がわかり、対策すべきか否か判断。P-MAXの必要性も自動判定。",
    demoType: "api",
    details: "GoogleマップのリンクまたはGBP名を入力するだけで、MEOスコア・口コミ状況・写真数・投稿頻度・NAP一貫性などを自動診断。P-MAX広告の必要性も自動で判定します。",
    icon: "🔍",
    status: "active",
    techStack: ["GBP API", "スコアリングエンジン", "P-MAX判定ロジック"],
  },
  {
    slug: "feature-045",
    title: "自社サイトへの記事投稿",
    category: "リード獲得・分析",
    description: "登録した店舗の紹介記事が、自社ドメインのサイトに自動生成される。SEO効果あり。",
    demoType: "publish",
    details: "登録された店舗情報をもとに紹介記事を自動生成し、自社ドメインのサイトに掲載。サイテーション効果とSEO効果を同時に獲得します。",
    icon: "📝",
    status: "active",
    techStack: ["AI記事生成", "CMS連携", "SEO最適化"],
  },
  {
    slug: "feature-046",
    title: "マイマップ作成",
    category: "リード獲得・分析",
    description: "業種、インフルエンサー、地域など任意の条件でカスタムマップを制作。",
    demoType: "settings",
    details: "業種・地域・インフルエンサーなど任意の条件でカスタムGoogleマイマップを自動生成。リード獲得やプロモーションに活用できます。",
    icon: "🗺️",
    status: "beta",
    techStack: ["Google Maps API", "マイマップAPI", "フィルタリング"],
  },
  {
    slug: "feature-047",
    title: "広告枠",
    category: "リード獲得・分析",
    description: "自社サイト内の広告枠を管理。リード獲得のための広告配置を最適化。",
    demoType: "settings",
    details: "自社プラットフォーム内の広告枠を管理。クリック率やコンバージョンデータに基づいて広告配置を最適化し、リード獲得効率を向上させます。",
    icon: "📊",
    status: "coming",
    techStack: ["広告配信エンジン", "A/Bテスト", "コンバージョン計測"],
  },
  {
    slug: "feature-048",
    title: "リードスコアリング",
    category: "リード獲得・分析",
    description: "店舗調査を行ったお客様の関心度をスコア化し、営業優先度を自動判定。",
    demoType: "analytics",
    details: "店舗調査の実施、資料ダウンロード、サイト訪問などの行動データをスコア化。HOT/WARM/COLDのステータスを自動判定し、営業効率を最大化します。",
    icon: "🎯",
    status: "active",
    techStack: ["スコアリングエンジン", "行動トラッキング", "CRM連携"],
  },
  {
    slug: "feature-049",
    title: "CRM連携",
    category: "リード獲得・分析",
    description: "見込み客の情報をSalesforce等の営業管理ツールに自動連携。",
    demoType: "api",
    details: "リード情報をSalesforceやHubSpotなどのCRMに自動連携。営業チームがスムーズにフォローアップできる体制を構築します。",
    icon: "🔄",
    status: "coming",
    techStack: ["Salesforce API", "HubSpot API", "Webhook"],
  },
  {
    slug: "feature-050",
    title: "業種別MEO成功事例の自動提示",
    category: "リード獲得・分析",
    description: "店舗調査結果に合わせて、同業種の改善事例やビフォーアフターを自動表示。",
    demoType: "analytics",
    details: "店舗診断の結果に基づき、同業種・同エリアのMEO成功事例を自動でレコメンド。ビフォーアフターデータで改善効果を具体的に提示します。",
    icon: "📈",
    status: "active",
    techStack: ["事例DB", "マッチングエンジン", "レコメンド"],
  },
  {
    slug: "feature-051",
    title: "業界情報コンテンツ配信",
    category: "リード獲得・分析",
    description: "週次・月次で計測データをもとに記事を作成し、自社サイトにコンテンツとして配信。",
    demoType: "publish",
    details: "業界の最新データや計測結果をもとにAIが記事を自動生成。定期的に自社サイトに配信することで、SEO効果とリード獲得を両立します。",
    icon: "📰",
    status: "beta",
    techStack: ["AI記事生成", "定期配信", "CMS連携"],
  },

  // ============================================================
  // サイテーション (citation)
  // ============================================================
  {
    slug: "feature-052",
    title: "多媒体同時投稿",
    category: "サイテーション",
    description: "GBPに更新した記事内容・写真がOTA/SNS/Webサイト等の他媒体に同時投稿される。",
    demoType: "api",
    details: "GBPに投稿した内容を食べログ・ホットペッパー・SNS・自社サイトなど複数媒体に同時配信。媒体ごとのフォーマットに自動変換します。",
    icon: "🔗",
    status: "active",
    techStack: ["マルチプラットフォームAPI", "フォーマット変換", "同期エンジン"],
  },
  {
    slug: "feature-053",
    title: "自社プラットフォーム掲載",
    category: "サイテーション",
    description: "自社システム利用店舗でプラットフォームを作成し、店舗情報を掲載。",
    demoType: "api",
    details: "Chubbyプラットフォーム上に店舗ページを自動生成。サイテーション効果を高め、自社ドメインのSEO価値を向上させます。",
    icon: "🌐",
    status: "active",
    techStack: ["自動ページ生成", "構造化データ", "SEO最適化"],
  },
  {
    slug: "feature-054",
    title: "サイテーション一貫性スコア",
    category: "サイテーション",
    description: "各媒体でのNAP情報の一致度をスコア化(0-100%)→不一致箇所をハイライト",
    demoType: "analytics",
    details: "全連携媒体のNAP情報を自動チェックし、一致度をパーセンテージで表示。不一致の箇所を色分けでハイライトし、修正すべき媒体を明確にします。",
    icon: "📊",
    status: "active",
    techStack: ["NAP比較エンジン", "スコアリング", "差分検出"],
  },
  {
    slug: "feature-055",
    title: "不正確な掲載情報の自動検出＆修正依頼",
    category: "サイテーション",
    description: "NAP不一致の媒体を自動検出し、修正リクエストを一括送信",
    demoType: "monitor",
    details: "各媒体のNAP情報を定期的にスキャンし、不一致を自動検出。ワンクリックで各媒体に修正リクエストを一括送信できます。",
    icon: "🔍",
    status: "active",
    techStack: ["定期スキャン", "自動検出", "修正リクエストAPI"],
  },
  {
    slug: "feature-056",
    title: "新規掲載先レコメンド",
    category: "サイテーション",
    description: "業種に合った未掲載の媒体（地域ポータル・業種特化サイト等）を自動提案。",
    demoType: "ai",
    details: "店舗の業種・エリア・ターゲット層に基づいて、まだ掲載されていない有効な媒体を自動提案。サイテーション数を効率的に増やします。",
    icon: "💡",
    status: "beta",
    techStack: ["媒体DB", "マッチングAI", "レコメンドエンジン"],
  },
  {
    slug: "feature-057",
    title: "構造化データで記事出力",
    category: "サイテーション",
    description: "サイテーション記事を構造化データ（Schema.org）付きで出力。",
    demoType: "api",
    details: "サイテーション記事にSchema.orgの構造化データを自動付与。検索エンジンやAIが情報を正確に理解できる形式で出力します。",
    icon: "📋",
    status: "coming",
    techStack: ["Schema.org", "JSON-LD生成", "バリデーター"],
  },
  {
    slug: "feature-058",
    title: "NAP情報の統一",
    category: "サイテーション",
    description: "全媒体のNAP情報を一括で統一管理。不一致を自動検出・修正。",
    demoType: "settings",
    details: "マスターNAP情報を設定し、全連携媒体のNAP情報を一括で統一。変更時も自動で全媒体に反映されます。",
    icon: "✅",
    status: "active",
    techStack: ["マスターデータ管理", "一括同期", "変更検知"],
  },

  // ============================================================
  // 多媒体管理 (media)
  // ============================================================
  {
    slug: "feature-059",
    title: "Instagram広告管理",
    category: "多媒体管理",
    description: "広告出稿、停止、数値すべてシステムで管理。分析結果も表示。",
    demoType: "analytics",
    details: "Instagram広告のキャンペーン作成・出稿・停止・KPI取得をシステム上で完結。リーチ・エンゲージメント・コンバージョンの分析ダッシュボードも提供します。",
    icon: "📸",
    status: "active",
    techStack: ["Meta Marketing API", "Instagram Insights API", "ダッシュボード"],
  },
  {
    slug: "feature-060",
    title: "TIKTOK広告管理",
    category: "多媒体管理",
    description: "TikTok Marketing APIで広告の出稿/停止/KPI取得→ダッシュボードに表示",
    demoType: "analytics",
    details: "TikTok Marketing APIを活用し、広告キャンペーンの作成・管理・KPI取得を一元化。動画広告のパフォーマンスをリアルタイムで監視します。",
    icon: "🎵",
    status: "active",
    techStack: ["TikTok Marketing API", "動画分析", "KPIダッシュボード"],
  },
  {
    slug: "feature-061",
    title: "EC管理",
    category: "多媒体管理",
    description: "ECサイトの広告、売上管理。",
    demoType: "settings",
    details: "ECサイトの広告出稿・売上データ・商品管理をシステム内で一元管理。オンラインとオフラインの売上を統合分析します。",
    icon: "🛒",
    status: "coming",
    techStack: ["EC API連携", "売上管理", "商品DB"],
  },
  {
    slug: "feature-062",
    title: "SNSから人気メニュー抜粋",
    category: "多媒体管理",
    description: "同ジャンルの他店舗で流行っているメニューをSNSから自動抽出。",
    demoType: "ai",
    details: "SNS上の投稿をAIが分析し、同業種の他店舗で話題のメニューやトレンドを自動抽出。自店舗のメニュー開発や投稿ネタに活用できます。",
    icon: "🔥",
    status: "beta",
    techStack: ["ソーシャルリスニング", "トレンド分析AI", "キーワード抽出"],
  },
  {
    slug: "feature-063",
    title: "SNS運用ツール",
    category: "多媒体管理",
    description: "Instagram、TikTok等のSNS投稿やインサイト分析を一元管理。",
    demoType: "publish",
    details: "各SNSプラットフォームへの投稿作成・予約・公開、およびインサイト分析を1つのダッシュボードで管理。クロスプラットフォームの運用効率を最大化します。",
    icon: "📱",
    status: "active",
    techStack: ["Instagram API", "TikTok API", "X API", "統合ダッシュボード"],
  },
  {
    slug: "feature-064",
    title: "食べログ/HP等の管理",
    category: "多媒体管理",
    description: "API連携でGoogle＋他媒体を一元管理。情報の一括更新。",
    demoType: "api",
    details: "食べログ・ホットペッパー・自社HPなど複数媒体の情報をAPI連携で一元管理。変更を一括で全媒体に反映します。",
    icon: "🍽️",
    status: "active",
    techStack: ["各媒体API", "一括更新", "差分管理"],
  },
  {
    slug: "feature-065",
    title: "マップ系API連携",
    category: "多媒体管理",
    description: "Yahoo!プレイス、Apple Maps等のマップサービスと連携。",
    demoType: "api",
    details: "Yahoo!プレイス・Apple Maps・Bing Placesなどの主要マップサービスと連携し、店舗情報を一括管理・同期します。",
    icon: "🗺️",
    status: "active",
    techStack: ["Yahoo! API", "Apple MapKit", "Bing Places API"],
  },
  {
    slug: "feature-066",
    title: "海外SNSに自動翻訳で投稿、インサイト管理",
    category: "多媒体管理",
    description: "大衆点評/RED/Snapchat等の海外SNS APIで自動投稿",
    demoType: "publish",
    details: "国内向け投稿を自動翻訳し、大衆点評・RED・Snapchat等の海外SNSに自動投稿。各プラットフォームのインサイトも一元管理します。",
    icon: "🌏",
    status: "coming",
    techStack: ["翻訳API", "海外SNS API", "インサイト集約"],
  },
  {
    slug: "feature-067",
    title: "最新Googleアップデート通知",
    category: "多媒体管理",
    description: "Googleのアルゴリズム変更等の最新情報をオンタイムで通知。",
    demoType: "monitor",
    details: "Googleの検索アルゴリズム変更・GBPの仕様変更・ポリシー更新などを常時監視し、影響のある変更があった場合に即時通知します。",
    icon: "📰",
    status: "active",
    techStack: ["RSSフィード", "変更検知", "通知API"],
  },
  {
    slug: "feature-068",
    title: "動画編集機能",
    category: "多媒体管理",
    description: "動画を編集してそのままSNSへ投稿。テンプレートも用意。",
    demoType: "publish",
    details: "ブラウザ上で動画のトリミング・テキスト追加・フィルタ適用が可能。テンプレートを使えば素早くプロ品質の動画を作成し、SNSに直接投稿できます。",
    icon: "🎬",
    status: "beta",
    techStack: ["動画編集SDK", "テンプレートエンジン", "SNS API"],
  },
  {
    slug: "feature-069",
    title: "POP作成",
    category: "多媒体管理",
    description: "AIで文字ベースの情報を入力すればPOPを自動デザイン。",
    demoType: "ai",
    details: "店舗情報やメニュー内容をテキストで入力すると、AIが店内POPを自動デザイン。印刷用データとして出力でき、発注までワンストップで対応。",
    icon: "🖼️",
    status: "coming",
    techStack: ["AI画像生成", "テンプレートデザイン", "PDF出力"],
  },
  {
    slug: "feature-070",
    title: "メニュー表作成",
    category: "多媒体管理",
    description: "AIで文字情報からメニュー表を作成。発注まで対応。",
    demoType: "ai",
    details: "メニュー情報をテキストで入力するだけで、AIがプロ品質のメニュー表をデザイン。多言語対応・印刷発注まで一貫して対応します。",
    icon: "📄",
    status: "coming",
    techStack: ["AIデザイン", "多言語翻訳", "印刷API"],
  },
  {
    slug: "feature-071",
    title: "公式LINEからのお知らせ",
    category: "多媒体管理",
    description: "定期配信＆イベント通知をLINE公式アカウントから自動送信。",
    demoType: "publish",
    details: "LINE Messaging APIを活用し、定期的なお知らせやイベント通知を公式LINEから自動配信。セグメント配信やリッチメッセージにも対応します。",
    icon: "💚",
    status: "active",
    techStack: ["LINE Messaging API", "セグメント配信", "リッチメッセージ"],
  },
  {
    slug: "feature-072",
    title: "クロスプラットフォーム統合カレンダー",
    category: "多媒体管理",
    description: "全SNS・全媒体の投稿スケジュールを1つのカレンダーで一元管理。",
    demoType: "settings",
    details: "GBP・Instagram・TikTok・Facebook・X・LINEなど全プラットフォームの投稿スケジュールを1つのカレンダーで表示・管理。投稿の重複や空白期間を防ぎます。",
    icon: "📅",
    status: "active",
    techStack: ["カレンダーUI", "マルチプラットフォーム同期", "スケジューラ"],
  },
  {
    slug: "feature-073",
    title: "ソーシャルリスニング",
    category: "多媒体管理",
    description: "SNS上で自店舗・ブランドに関する言及を自動収集＆通知。",
    demoType: "monitor",
    details: "Instagram・X・TikTokなどのSNS上で自店舗に関する言及をリアルタイムで収集。ポジティブな投稿は再利用候補として、ネガティブな投稿はアラートとして通知します。",
    icon: "👂",
    status: "active",
    techStack: ["ソーシャルリスニングAPI", "感情分析", "リアルタイム通知"],
  },
  {
    slug: "feature-074",
    title: "UGC（ユーザー生成コンテンツ）収集",
    category: "多媒体管理",
    description: "お客様がSNSに投稿した写真・動画を自動収集し、許可を得て再利用",
    demoType: "monitor",
    details: "ハッシュタグやメンション経由でお客様のSNS投稿を自動収集。許可取得フローを経て、自店舗のマーケティング素材として再利用できます。",
    icon: "📷",
    status: "beta",
    techStack: ["SNS API", "許可管理", "メディアライブラリ"],
  },

  // ============================================================
  // 基礎情報管理 (basic-info)
  // ============================================================
  {
    slug: "feature-075",
    title: "情報変更の自動検知",
    category: "基礎情報管理",
    description: "Googleが勝手に営業時間等を変更した場合に即時アラート。自動で元に戻すことも可能。",
    demoType: "monitor",
    details: "GBPの基礎情報を定期的にスキャンし、Googleによる自動変更や第三者による改ざんを即時検知。設定に応じて自動で元に戻すことも可能です。",
    icon: "🚨",
    status: "active",
    techStack: ["GBP API", "定期スキャン", "自動復旧"],
  },
  {
    slug: "feature-076",
    title: "第三者による改ざん防止",
    category: "基礎情報管理",
    description: "第三者による情報変更をシャットアウト。変更をブロックしログに記録。",
    demoType: "monitor",
    details: "オーナー以外による情報変更を監視し、不正な変更を検知した場合に即座にブロック・復旧。全ての変更履歴をログに記録します。",
    icon: "🛡️",
    status: "active",
    techStack: ["変更監視", "自動ブロック", "監査ログ"],
  },
  {
    slug: "feature-077",
    title: "外国語ページ作成",
    category: "基礎情報管理",
    description: "Googleが提供している各言語ページを自動作成。英語・韓国語・中国語等。",
    demoType: "ai",
    details: "GBPの多言語機能を活用し、英語・中国語・韓国語など主要言語のページを自動生成。インバウンド観光客への対応力を強化します。",
    icon: "🌍",
    status: "active",
    techStack: ["GBP API", "翻訳AI", "多言語管理"],
  },
  {
    slug: "feature-078",
    title: "写真重複アラート",
    category: "基礎情報管理",
    description: "重複している写真がある場合にアラートで通知。重複写真の特定も可能。",
    demoType: "monitor",
    details: "GBPに登録されている全写真の重複チェックを定期実行。重複が見つかった場合にアラートで通知し、どの写真が重複しているかを具体的に表示します。",
    icon: "📷",
    status: "active",
    techStack: ["画像ハッシュ比較", "定期チェック", "通知"],
  },
  {
    slug: "feature-079",
    title: "NAP情報の確認",
    category: "基礎情報管理",
    description: "各媒体のNAP（Name/Address/Phone）情報をクロスチェック。不一致を自動検出。",
    demoType: "analytics",
    details: "GBP・食べログ・ホットペッパー・自社HPなど全媒体のNAP情報を横断的にチェック。不一致箇所をテーブル形式で可視化します。",
    icon: "✅",
    status: "active",
    techStack: ["マルチAPI", "NAP比較", "クロスチェックエンジン"],
  },
  {
    slug: "feature-080",
    title: "カテゴリの最適解提案",
    category: "基礎情報管理",
    description: "業種・エリアに基づいてMEOに最適なカテゴリの組み合わせをAIが提案。",
    demoType: "ai",
    details: "店舗の業種・エリア・競合状況を分析し、MEO効果を最大化するカテゴリの組み合わせをAIが提案。メインカテゴリとサブカテゴリの最適解を導きます。",
    icon: "🏷️",
    status: "active",
    techStack: ["カテゴリDB", "競合分析", "AI提案"],
  },
  {
    slug: "feature-081",
    title: "メニュー一括追加",
    category: "基礎情報管理",
    description: "CSVアップロードでメニュー・商品・サービスを一括登録。多言語翻訳も自動。",
    demoType: "settings",
    details: "CSV/Excelファイルをアップロードするだけで、メニュー・商品・サービスをGBPに一括登録。多言語翻訳も自動で行います。",
    icon: "🍽️",
    status: "active",
    techStack: ["CSV/Excelパーサー", "GBP API", "翻訳API"],
  },
  {
    slug: "feature-082",
    title: "メニュー・商品の編集",
    category: "基礎情報管理",
    description: "システムから直接変更可能。手動・自動どちらにも対応。行の追加・削除も簡単。",
    demoType: "settings",
    details: "GBPのメニュー・商品・サービス情報をシステム上で直接編集。行の追加・削除・並び替えが直感的に操作でき、変更は即座にGBPに反映されます。",
    icon: "✏️",
    status: "active",
    techStack: ["インラインエディタ", "GBP API", "リアルタイム同期"],
  },
  {
    slug: "feature-083",
    title: "写真・動画のデータベース",
    category: "基礎情報管理",
    description: "写真や動画を一元管理できるストレージ機能。各媒体への配信元として利用。",
    demoType: "settings",
    details: "全ての写真・動画を一元管理するメディアライブラリ。タグ付け・検索・フィルタリングに対応し、各媒体への配信元として活用できます。",
    icon: "💾",
    status: "beta",
    techStack: ["クラウドストレージ", "メディア管理", "タグシステム"],
  },
  {
    slug: "feature-084",
    title: "祝日・特別営業時間の一括管理",
    category: "基礎情報管理",
    description: "年末年始・GW・お盆等の特別営業時間をカレンダー形式で事前設定＆自動反映。",
    demoType: "settings",
    details: "祝日・年末年始・GW・お盆などの特別営業時間をカレンダー形式で事前設定。設定した日時にGBPへ自動反映されます。",
    icon: "📅",
    status: "active",
    techStack: ["カレンダーUI", "GBP Special Hours API", "自動反映"],
  },
  {
    slug: "feature-085",
    title: "GBP属性の充実度チェック",
    category: "基礎情報管理",
    description: "設定可能な属性のうち未設定の項目をリスト化して提案。充実度を%で表示。",
    demoType: "analytics",
    details: "GBPで設定可能な全属性のうち、未設定の項目をリスト化。充実度をパーセンテージで表示し、優先的に設定すべき属性を提案します。",
    icon: "📋",
    status: "active",
    techStack: ["GBP Attributes API", "チェックリスト", "レコメンド"],
  },
  {
    slug: "feature-086",
    title: "パンくず機能",
    category: "基礎情報管理",
    description: "GBP内のナビゲーション構造を最適化。",
    demoType: "settings",
    details: "GBPのカテゴリ・サービス・メニューの階層構造を最適化し、ユーザーのナビゲーション体験を向上させます。",
    icon: "🔗",
    status: "coming",
    techStack: ["構造化データ", "カテゴリ最適化", "GBP API"],
  },

  // ============================================================
  // P-MAX広告 (pmax)
  // ============================================================
  {
    slug: "feature-087",
    title: "広告文の自動作成",
    category: "P-MAX広告",
    description: "口コミからお客様が喜んでいる内容をピックアップして広告文を作成。過去の型も参照。",
    demoType: "ai",
    details: "口コミのポジティブキーワードを分析し、実際のお客様の声をベースにした広告文を自動生成。過去の高パフォーマンス広告のパターンも参照します。",
    icon: "📝",
    status: "active",
    techStack: ["NLP", "広告テキスト生成AI", "Google Ads API"],
  },
  {
    slug: "feature-088",
    title: "キーワード自動作成",
    category: "P-MAX広告",
    description: "過去の実績データからその店舗に合ったキーワードを自動生成。",
    demoType: "ai",
    details: "過去の広告パフォーマンスデータと検索クエリを分析し、各店舗に最適なキーワードを自動生成。新規キーワードの発見にも貢献します。",
    icon: "🔑",
    status: "active",
    techStack: ["Google Ads API", "キーワードプランナー", "AI分析"],
  },
  {
    slug: "feature-089",
    title: "サイトリンクの作成",
    category: "P-MAX広告",
    description: "雛形通りにサイトリンクアセットを自動作成。",
    demoType: "settings",
    details: "店舗情報とWebサイトの構成に基づいて、サイトリンクアセットを自動生成。メニュー・アクセス・予約などの主要ページへのリンクを設定します。",
    icon: "🔗",
    status: "active",
    techStack: ["Google Ads API", "テンプレートエンジン", "URL検証"],
  },
  {
    slug: "feature-090",
    title: "コールアウトの作成",
    category: "P-MAX広告",
    description: "雛形通りにコールアウトアセットを自動作成。",
    demoType: "settings",
    details: "店舗の強み・特徴をAIが分析し、コールアウトアセットを自動生成。「個室完備」「駐車場あり」などの訴求ポイントを効果的に設定します。",
    icon: "📢",
    status: "active",
    techStack: ["Google Ads API", "特徴抽出AI", "テンプレート"],
  },
  {
    slug: "feature-091",
    title: "構造化スニペットの作成",
    category: "P-MAX広告",
    description: "雛形通りに構造化スニペットアセットを自動作成。",
    demoType: "settings",
    details: "業種に適した構造化スニペットのヘッダーと値を自動生成。メニューカテゴリ・サービス内容・対応エリアなどを効果的に表示します。",
    icon: "📋",
    status: "active",
    techStack: ["Google Ads API", "カテゴリ分析", "自動生成"],
  },
  {
    slug: "feature-092",
    title: "P-MAXレポート作成",
    category: "P-MAX広告",
    description: "雛形通りにパフォーマンスレポートを自動生成。クライアントへの報告用。",
    demoType: "analytics",
    details: "P-MAXキャンペーンのKPIを自動集計し、クライアント向けレポートを自動生成。PDF出力にも対応し、月次報告を効率化します。",
    icon: "📊",
    status: "active",
    techStack: ["Google Ads API", "レポート生成", "PDF出力"],
  },
  {
    slug: "feature-093",
    title: "ターゲット設定",
    category: "P-MAX広告",
    description: "過去の実績から店舗に合ったターゲティングを自動設定。",
    demoType: "settings",
    details: "過去のコンバージョンデータを分析し、最適なオーディエンスシグナル・地域ターゲティング・デモグラフィックを自動設定します。",
    icon: "🎯",
    status: "active",
    techStack: ["Google Ads API", "オーディエンス分析", "AI最適化"],
  },
  {
    slug: "feature-094",
    title: "実数値の自動計測",
    category: "P-MAX広告",
    description: "決められた型を自動で広告キャンペーンごとに計測・レポート。",
    demoType: "analytics",
    details: "クリック数・CV数・CPA・ROASなどの主要KPIを広告キャンペーンごとに自動計測。決められたフォーマットでレポートに反映します。",
    icon: "📈",
    status: "active",
    techStack: ["Google Ads API", "自動計測", "データパイプライン"],
  },
  {
    slug: "feature-095",
    title: "アカウント〜キャンペーン作成",
    category: "P-MAX広告",
    description: "広告管理画面を開かずに、サイト上でアカウント作成からキャンペーン作成まで完結。",
    demoType: "settings",
    details: "Google Ads管理画面を開くことなく、本システム上でアカウント作成・MCC連携・P-MAXキャンペーン作成まで全て完結。操作を大幅に簡素化します。",
    icon: "⚙️",
    status: "active",
    techStack: ["Google Ads API", "MCC連携", "ウィザードUI"],
  },
  {
    slug: "feature-096",
    title: "予算最適化レコメンド",
    category: "P-MAX広告",
    description: "AIが過去のパフォーマンスから最適な日予算・月予算を提案。",
    demoType: "ai",
    details: "過去のパフォーマンスデータをAIが分析し、ROASを最大化する日予算・月予算を自動提案。曜日や時間帯ごとの配分最適化も行います。",
    icon: "💰",
    status: "active",
    techStack: ["予算最適化AI", "パフォーマンス分析", "シミュレーション"],
  },
  {
    slug: "feature-097",
    title: "LP自動生成",
    category: "P-MAX広告",
    description: "店舗情報から広告用LPを自動生成。検索語句に合わせてリアルタイムで最適化。",
    demoType: "ai",
    details: "店舗情報・口コミ・写真をもとに広告用ランディングページを自動生成。検索語句に応じてコンテンツをリアルタイムで最適化します。",
    icon: "🌐",
    status: "beta",
    techStack: ["LP生成AI", "動的コンテンツ", "A/Bテスト"],
  },
  {
    slug: "feature-098",
    title: "業種別の平均値",
    category: "P-MAX広告",
    description: "同じシステムを使っている店舗の業種別平均値でスコアリングし、改善分析。",
    demoType: "analytics",
    details: "Chubbyプラットフォーム利用店舗の業種別平均KPIを算出し、自店舗の広告パフォーマンスと比較。改善すべきポイントを明確にします。",
    icon: "📉",
    status: "active",
    techStack: ["ベンチマークDB", "統計分析", "比較レポート"],
  },
  {
    slug: "feature-099",
    title: "多媒体連動（P-MAX）",
    category: "P-MAX広告",
    description: "システムで広告文等を変更した際、他媒体の情報も同時に更新。",
    demoType: "api",
    details: "P-MAXの広告文やアセットを変更すると、連動する他媒体（SNS・Webサイト等）の情報も同時に更新。一貫性のあるマーケティングを実現します。",
    icon: "🔄",
    status: "coming",
    techStack: ["マルチプラットフォーム同期", "変更検知", "一括更新"],
  },
  {
    slug: "feature-100",
    title: "成果悪化時の改善案",
    category: "P-MAX広告",
    description: "パフォーマンスが悪化した際にAIが改善案を自動提案。",
    demoType: "ai",
    details: "KPIの悪化を自動検知し、原因分析と改善案をAIが自動提案。予算配分・クリエイティブ・ターゲティングの具体的な改善アクションを提示します。",
    icon: "🔧",
    status: "active",
    techStack: ["異常検知AI", "根本原因分析", "改善提案エンジン"],
  },

  // ============================================================
  // 広告管理 (ads)
  // ============================================================
  {
    slug: "feature-101",
    title: "Google広告アカウント作成・MCC連携",
    category: "広告管理",
    description: "アカウント作成、MCC配下管理、認証連携をシステム上で完結。",
    demoType: "auth",
    details: "Google広告アカウントの新規作成とMCC（管理者アカウント）配下への紐付けをシステム上で完結。OAuth認証によるセキュアな連携を提供します。",
    icon: "🔍",
    status: "active",
    techStack: ["Google Ads API", "MCC管理", "OAuth 2.0"],
  },
  {
    slug: "feature-102",
    title: "Google P-Maxキャンペーン運用",
    category: "広告管理",
    description: "P-Max作成、Asset Group管理、予算・入札・地域設定",
    demoType: "settings",
    details: "P-MAXキャンペーンの作成から、アセットグループ管理、予算設定、入札戦略、地域ターゲティングまで全てシステム上で操作可能です。",
    icon: "📢",
    status: "active",
    techStack: ["Google Ads API v17", "P-MAX管理", "アセット管理"],
  },
  {
    slug: "feature-103",
    title: "Google広告レポート取得",
    category: "広告管理",
    description: "キャンペーン別・アセット別・日次KPIを自動取得・表示。",
    demoType: "analytics",
    details: "Google広告のレポートデータをキャンペーン別・アセット別・日次で自動取得。ダッシュボードにKPIをリアルタイム表示します。",
    icon: "📊",
    status: "active",
    techStack: ["Google Ads Reporting API", "データ可視化", "自動集計"],
  },
  {
    slug: "feature-104",
    title: "Meta広告アカウント/BM連携",
    category: "広告管理",
    description: "Business Manager、広告アカウント、権限の一括連携。",
    demoType: "auth",
    details: "Meta Business Manager・広告アカウント・Instagramアカウントの連携を一括で設定。権限管理もシステム上で完結します。",
    icon: "📱",
    status: "active",
    techStack: ["Meta Business API", "Business Manager", "OAuth"],
  },
  {
    slug: "feature-105",
    title: "Meta広告キャンペーン運用",
    category: "広告管理",
    description: "Campaign / Ad Set / Ad / Creative 作成・更新・停止。",
    demoType: "settings",
    details: "Meta広告のキャンペーン・広告セット・広告・クリエイティブの全階層をシステム上で作成・編集・停止。Facebook/Instagram両面に対応します。",
    icon: "📸",
    status: "active",
    techStack: ["Meta Marketing API", "キャンペーン管理", "クリエイティブ管理"],
  },
  {
    slug: "feature-106",
    title: "Meta広告レポート取得",
    category: "広告管理",
    description: "KPIをアカウント/キャンペーン/広告セット/広告粒度で分析。",
    demoType: "analytics",
    details: "Meta広告のKPIを各階層（アカウント・キャンペーン・広告セット・広告）で取得し、詳細な分析ダッシュボードを提供します。",
    icon: "📈",
    status: "active",
    techStack: ["Meta Insights API", "多階層分析", "レポート生成"],
  },
  {
    slug: "feature-107",
    title: "Threads広告配信",
    category: "広告管理",
    description: "Threadsフィード面への広告配信。",
    demoType: "publish",
    details: "Threadsのフィード面に広告を配信。Meta広告との連携により、効率的なクロスプラットフォーム広告運用を実現します。",
    icon: "🧵",
    status: "coming",
    techStack: ["Threads API", "Meta Marketing API", "広告配信"],
  },
  {
    slug: "feature-108",
    title: "TikTok広告キャンペーン運用",
    category: "広告管理",
    description: "広告作成、管理、データ取得をシステム上で完結。",
    demoType: "settings",
    details: "TikTok広告のキャンペーン作成・クリエイティブ管理・パフォーマンスデータ取得をシステム上で一元管理します。",
    icon: "🎵",
    status: "active",
    techStack: ["TikTok Marketing API", "キャンペーン管理", "レポート"],
  },
  {
    slug: "feature-109",
    title: "TikTok広告イベント計測",
    category: "広告管理",
    description: "Web/App/Offlineのイベント送信、最適化用CV連携。",
    demoType: "analytics",
    details: "TikTok Events APIを活用し、Web・アプリ・オフラインのコンバージョンイベントを計測・送信。広告最適化のためのデータフィードバックを実現します。",
    icon: "📲",
    status: "active",
    techStack: ["TikTok Events API", "CV計測", "Pixel管理"],
  },
  {
    slug: "feature-110",
    title: "X広告アカウント作成",
    category: "広告管理",
    description: "X広告アカウント開設、課金情報設定をシステム内で。",
    demoType: "auth",
    details: "X（Twitter）広告アカウントの開設と課金情報の設定をシステム内で完結。APIによる自動化で手間を削減します。",
    icon: "🐦",
    status: "beta",
    techStack: ["X Ads API", "アカウント管理", "課金設定"],
  },
  {
    slug: "feature-111",
    title: "X広告キャンペーン運用",
    category: "広告管理",
    description: "キャンペーン、ターゲティング、クリエイティブ、分析の自動化。",
    demoType: "settings",
    details: "X広告のキャンペーン作成・ターゲティング設定・クリエイティブ管理・パフォーマンス分析を自動化。効率的なX広告運用を支援します。",
    icon: "📣",
    status: "beta",
    techStack: ["X Ads API", "ターゲティング", "クリエイティブ管理"],
  },
  {
    slug: "feature-112",
    title: "Xコンバージョン計測",
    category: "広告管理",
    description: "Webコンバージョン計測、最適化用イベント送信。",
    demoType: "analytics",
    details: "X広告のWebコンバージョンを計測し、最適化用イベントを自動送信。広告効果の正確な把握と自動最適化を実現します。",
    icon: "🎯",
    status: "beta",
    techStack: ["X Conversion API", "イベント計測", "最適化"],
  },

  // ============================================================
  // オーガニック投稿 (organic)
  // ============================================================
  {
    slug: "feature-113",
    title: "Instagram投稿連携",
    category: "オーガニック投稿",
    description: "画像・動画・リール等の投稿予約/投稿をシステム上で完結。",
    demoType: "publish",
    details: "Instagram Content Publishing APIを活用し、画像・動画・リール・カルーセルの投稿をシステム上で作成・予約・公開。メディアアップロードから公開まで一元管理します。",
    icon: "📸",
    status: "active",
    techStack: ["Instagram Content Publishing API", "メディア管理", "予約投稿"],
  },
  {
    slug: "feature-114",
    title: "Facebook投稿連携",
    category: "オーガニック投稿",
    description: "Facebookページ投稿、更新、削除、返信を一元管理。",
    demoType: "publish",
    details: "Facebook Pages APIでページ投稿の作成・更新・削除・コメント返信を一元管理。投稿のインサイト取得にも対応します。",
    icon: "📘",
    status: "active",
    techStack: ["Facebook Pages API", "コメント管理", "インサイト"],
  },
  {
    slug: "feature-115",
    title: "TikTok投稿連携",
    category: "オーガニック投稿",
    description: "TikTokへの直接投稿または下書き送信。",
    demoType: "publish",
    details: "TikTok Content Posting APIで動画をアップロードし、直接公開または下書きとして保存。アプリを開かずにシステム上で完結します。",
    icon: "🎵",
    status: "active",
    techStack: ["TikTok Content Posting API", "動画アップロード", "下書き管理"],
  },
  {
    slug: "feature-116",
    title: "X投稿連携",
    category: "オーガニック投稿",
    description: "Xへの投稿、スレッド投稿、メディア付き投稿。",
    demoType: "publish",
    details: "X API v2を使用してテキスト・画像・動画付きポスト、スレッド投稿を作成。スケジュール投稿にも対応します。",
    icon: "🐦",
    status: "active",
    techStack: ["X API v2", "メディアアップロード", "スレッド管理"],
  },
  {
    slug: "feature-117",
    title: "Threads投稿連携",
    category: "オーガニック投稿",
    description: "Threadsへのテキスト/画像/動画/カルーセル投稿。",
    demoType: "publish",
    details: "Threads APIでテキスト・画像・動画・カルーセル形式の投稿を作成・公開。MetaのSNSエコシステムとの連携を最大限活用します。",
    icon: "🧵",
    status: "active",
    techStack: ["Threads API", "コンテンツ管理", "カルーセル生成"],
  },
  {
    slug: "feature-118",
    title: "GBP基本情報・投稿管理",
    category: "オーガニック投稿",
    description: "店舗情報更新、投稿、複数拠点管理をシステム内で完結。",
    demoType: "settings",
    details: "GBPの基本情報更新・最新情報投稿・写真管理を複数拠点分まとめてシステム内で完結。拠点ごとの個別設定にも対応します。",
    icon: "🔍",
    status: "active",
    techStack: ["GBP API", "マルチロケーション", "一括管理"],
  },
  {
    slug: "feature-119",
    title: "GBPパフォーマンス取得",
    category: "オーガニック投稿",
    description: "検索表示、アクション、店舗パフォーマンスを自動取得。",
    demoType: "analytics",
    details: "GBP Performance APIで検索表示回数・プロフィール閲覧数・アクション（電話・経路検索・Webクリック）を自動取得しダッシュボードに表示します。",
    icon: "📊",
    status: "active",
    techStack: ["GBP Performance API", "自動集計", "KPIダッシュボード"],
  },
  {
    slug: "feature-120",
    title: "GBPレビュー/通知連携",
    category: "オーガニック投稿",
    description: "レビュー取得、返信、更新通知をリアルタイム受信。",
    demoType: "monitor",
    details: "GBPのレビュー投稿をリアルタイムで検知し、通知を配信。レビューへの返信もシステム上で完結し、更新通知でタイムリーな対応を支援します。",
    icon: "💬",
    status: "active",
    techStack: ["GBP Reviews API", "Webhook", "リアルタイム通知"],
  },
  {
    slug: "feature-121",
    title: "投稿スケジューラ/承認フロー",
    category: "オーガニック投稿",
    description: "予約投稿、公開前レビュー、差戻し、承認履歴を管理。",
    demoType: "settings",
    details: "投稿の予約・公開前レビュー・承認・差戻しのワークフローを管理。承認履歴も記録され、チーム運用での品質管理を実現します。",
    icon: "📋",
    status: "active",
    techStack: ["ワークフローエンジン", "承認管理", "通知"],
  },

  // ============================================================
  // OTA連携 (ota)
  // ============================================================
  {
    slug: "feature-122",
    title: "TripAdvisor Content API連携",
    category: "OTA連携",
    description: "施設情報、写真、レビュー、位置情報の取得/表示。",
    demoType: "api",
    details: "TripAdvisor Content APIで施設情報・写真・レビュー・位置情報を取得し、ダッシュボードに統合表示。OTAの評判管理を一元化します。",
    icon: "🦉",
    status: "active",
    techStack: ["TripAdvisor Content API", "レビュー管理", "施設情報同期"],
  },
  {
    slug: "feature-123",
    title: "TripAdvisor Hotel Pricing API",
    category: "OTA連携",
    description: "予約導線用の価格表示・送客。",
    demoType: "api",
    details: "TripAdvisor Hotel Pricing APIで料金情報を取得し、予約導線を構築。送客効果の計測も行います。",
    icon: "💰",
    status: "active",
    techStack: ["TripAdvisor Pricing API", "料金比較", "予約導線"],
  },
  {
    slug: "feature-124",
    title: "Booking.com Connectivity API",
    category: "OTA連携",
    description: "施設情報、在庫、料金、予約などの同期。",
    demoType: "api",
    details: "Booking.com Connectivity APIで施設情報・在庫・料金・予約をリアルタイム同期。ダブルブッキングを防止し、効率的な在庫管理を実現します。",
    icon: "🏨",
    status: "active",
    techStack: ["Booking.com API", "在庫同期", "予約管理"],
  },
  {
    slug: "feature-125",
    title: "Booking.com Messaging連携",
    category: "OTA連携",
    description: "接続承認管理、ゲストメッセージ運用。",
    demoType: "api",
    details: "Booking.comのゲストメッセージをシステム上で一元管理。接続承認やメッセージテンプレートにも対応します。",
    icon: "💬",
    status: "active",
    techStack: ["Booking.com Messaging API", "チャット管理", "テンプレート"],
  },
  {
    slug: "feature-126",
    title: "Expedia施設オンボーディング",
    category: "OTA連携",
    description: "施設の新規登録・更新・状態取得。",
    demoType: "api",
    details: "Expedia Rapid APIで施設の新規登録・情報更新・ステータス取得を行い、Expediaグループへのオンボーディングを自動化します。",
    icon: "✈️",
    status: "beta",
    techStack: ["Expedia Rapid API", "施設登録", "ステータス管理"],
  },
  {
    slug: "feature-127",
    title: "Expedia在庫・料金・予約連携",
    category: "OTA連携",
    description: "在庫・料金更新、予約通知/取得、予約ライフサイクル管理。",
    demoType: "api",
    details: "Expedia APIで在庫・料金をリアルタイム更新し、予約の通知・取得・ライフサイクル管理を自動化します。",
    icon: "📦",
    status: "beta",
    techStack: ["Expedia API", "在庫管理", "予約ライフサイクル"],
  },
  {
    slug: "feature-128",
    title: "Vrbo連携",
    category: "OTA連携",
    description: "Vrboの掲載、予約、レビュー等との連携。",
    demoType: "api",
    details: "Vrboとの連携により、掲載情報・予約・レビューを一元管理。バケーションレンタル市場への対応を強化します。",
    icon: "🏡",
    status: "coming",
    techStack: ["Vrbo API", "掲載管理", "予約同期"],
  },
  {
    slug: "feature-129",
    title: "Agoda連携",
    category: "OTA連携",
    description: "Agoda上の在庫・料金・予約運用。",
    demoType: "api",
    details: "Agodaとの連携で在庫・料金・予約をリアルタイム同期。アジア市場向けのOTA運用を効率化します。",
    icon: "🌏",
    status: "coming",
    techStack: ["Agoda API", "在庫同期", "料金管理"],
  },
  {
    slug: "feature-130",
    title: "Airbnb連携",
    category: "OTA連携",
    description: "掲載情報・予約・通知・運用連携。",
    demoType: "api",
    details: "Airbnbとの連携で掲載情報の同期・予約管理・通知受信を自動化。民泊・体験型宿泊の運用を一元管理します。",
    icon: "🏠",
    status: "coming",
    techStack: ["Airbnb API", "掲載同期", "予約管理"],
  },
  {
    slug: "feature-131",
    title: "OTAチャネルマネージャー",
    category: "OTA連携",
    description: "複数OTAを一括運用するための共通ハブ。在庫・料金の一元管理。",
    demoType: "settings",
    details: "全OTAの在庫・料金・予約を一元管理するチャネルマネージャー。ダブルブッキング防止・料金一括更新・予約統合管理を提供します。",
    icon: "🔄",
    status: "active",
    techStack: ["チャネルマネージャー", "在庫同期", "料金エンジン"],
  },

  // ============================================================
  // チャットボット (chatbot)
  // ============================================================
  {
    slug: "feature-132",
    title: "MEOについての質問コーナー",
    category: "チャットボット",
    description: "チャットボットで削除申請の仕方、投稿方法などをすぐに確認。",
    demoType: "ai",
    details: "MEOに関するあらゆる質問にAIチャットボットが即座に回答。口コミ削除申請の方法、投稿のやり方、順位改善のコツなどを対話形式で学べます。",
    icon: "❓",
    status: "active",
    techStack: ["LLM", "ナレッジベース", "チャットUI"],
  },
  {
    slug: "feature-133",
    title: "LINEでの変更指示",
    category: "チャットボット",
    description: "LINEで基礎情報の変更依頼、口コミ返信、削除申請などが可能。",
    demoType: "api",
    details: "LINE公式アカウントを通じて、営業時間変更・口コミ返信・削除申請などの操作指示が可能。外出先からでもスマホで簡単に操作できます。",
    icon: "💚",
    status: "active",
    techStack: ["LINE Messaging API", "コマンド解析", "API連携"],
  },
  {
    slug: "feature-134",
    title: "AIカスタマーセンター",
    category: "チャットボット",
    description: "チャットツールと連携して使用。MEOに関するあらゆる質問に対応。",
    demoType: "ai",
    details: "Slack・Teams・LINEなどのチャットツールと連携し、MEOに関する質問に24時間対応するAIカスタマーセンター。操作方法から戦略相談まで幅広くサポートします。",
    icon: "🤖",
    status: "active",
    techStack: ["LLM", "チャット連携API", "FAQ DB"],
  },
  {
    slug: "feature-135",
    title: "タスク追いかけボット",
    category: "チャットボット",
    description: "ゲームのクエストのように、日々のMEO作業をタスク化してモチベーション管理。",
    demoType: "settings",
    details: "日々のMEO作業（口コミ返信・投稿・写真アップロードなど）をクエスト形式でタスク化。完了するとXPが貯まりレベルアップする仕組みで、モチベーションを維持します。",
    icon: "🎮",
    status: "beta",
    techStack: ["ゲーミフィケーション", "タスク管理", "XPシステム"],
  },

  // ============================================================
  // システム管理 (admin)
  // ============================================================
  {
    slug: "feature-136",
    title: "売上分析AI",
    category: "システム管理",
    description: "POSレジ・天気データ・地域イベントデータを組み合わせた売上分析AI。曜日・時間帯・商品別の時系列データ分析。",
    demoType: "analytics",
    details: "POSレジの売上データ・天気情報・地域イベントデータをAIが統合分析。曜日・時間帯・商品別のトレンドを発見し、売上予測と改善提案を行います。",
    icon: "📊",
    status: "active",
    techStack: ["売上分析AI", "POSレジ連携", "天気API", "予測モデル"],
  },
  {
    slug: "feature-137",
    title: "データで賢くなる仕組み",
    category: "システム管理",
    description: "Pinecone/pgvector等のベクトルDBを活用。データが増えるほど引き出せる事例が増え、AIの提案精度が向上。",
    demoType: "api",
    details: "ベクトルデータベースに全店舗のデータを蓄積。データが増えるほどAIの提案精度が向上し、類似事例の検索・レコメンドが高度化します。",
    icon: "🧠",
    status: "active",
    techStack: ["Pinecone", "pgvector", "Embedding API", "RAG"],
  },
  {
    slug: "feature-138",
    title: "メール送信（Resend / SendGrid）",
    category: "システム管理",
    description: "口コミ通知・週次レポート送信・アラートメール・ユーザー招待",
    demoType: "api",
    details: "Resend/SendGridを活用し、口コミ通知・週次レポート・アラートメール・ユーザー招待などのメール配信を自動化します。",
    icon: "📧",
    status: "active",
    techStack: ["Resend", "SendGrid", "メールテンプレート"],
  },

  // ============================================================
  // ランキング・順位追跡 (ranking)
  // ============================================================
  {
    slug: "feature-139",
    title: "MEOランキング検索・順位追跡",
    category: "ランキング・順位追跡",
    description: "対策キーワード×曜日×時間帯別に検索順位を自動取得。Google Maps APIで定期計測。",
    demoType: "analytics",
    details: "設定したキーワード・曜日・時間帯の組み合わせでGoogle Maps検索順位を自動取得。バッチ処理で定期計測し、順位変動をリアルタイムで追跡します。",
    icon: "📍",
    status: "active",
    techStack: ["Google Maps API", "バッチ処理", "Cron", "順位計測エンジン"],
  },
  {
    slug: "feature-140",
    title: "ランキング推移チャート",
    category: "ランキング・順位追跡",
    description: "キーワード別の順位推移を折れ線グラフで可視化。日次・週次・月次切り替え。",
    demoType: "analytics",
    details: "各キーワードの検索順位を時系列グラフで表示。目標順位ラインを基準線として表示し、日次・週次・月次で切り替え可能。施策の効果を視覚的に把握できます。",
    icon: "📈",
    status: "active",
    techStack: ["Recharts", "データ集計", "時系列分析"],
  },
  {
    slug: "feature-141",
    title: "ランキング検索設定",
    category: "ランキング・順位追跡",
    description: "店舗ごとに対策キーワード・計測曜日・計測時間帯を設定。複数キーワード対応。",
    demoType: "settings",
    details: "各店舗のランキング計測条件を細かく設定。キーワード・曜日（0-6）・時間帯（0-23）の組み合わせで計測スケジュールを管理します。",
    icon: "⚙️",
    status: "active",
    techStack: ["設定管理UI", "Cronスケジューラ", "GBP API"],
  },
  {
    slug: "feature-142",
    title: "競合順位比較",
    category: "ランキング・順位追跡",
    description: "同一キーワードで自店舗と競合店舗の順位を並べて比較。差分をハイライト。",
    demoType: "analytics",
    details: "対策キーワードごとに自店舗と設定した競合店舗の順位を並列表示。順位差の変動をハイライトし、競合との相対的なポジションを把握できます。",
    icon: "🏁",
    status: "active",
    techStack: ["Google Maps API", "競合比較", "差分表示"],
  },
  {
    slug: "feature-143",
    title: "順位変動アラート",
    category: "ランキング・順位追跡",
    description: "順位が急落・急上昇した場合に即時通知。閾値はキーワードごとに設定可能。",
    demoType: "monitor",
    details: "設定した閾値を超える順位変動が発生した場合に即時アラートを発信。急落時は原因分析のヒントも提示します。",
    icon: "🚨",
    status: "active",
    techStack: ["変動検知", "閾値管理", "通知API"],
  },
  {
    slug: "feature-144",
    title: "エリア別順位ヒートマップ",
    category: "ランキング・順位追跡",
    description: "地図上にエリア別の検索順位をヒートマップ表示。商圏分析に活用。",
    demoType: "analytics",
    details: "対策エリア内の各地点での検索順位を地図上にヒートマップで可視化。商圏の強さ・弱さを直感的に把握し、対策エリアの最適化に活用できます。",
    icon: "🗺️",
    status: "beta",
    techStack: ["Google Maps API", "ヒートマップ", "商圏分析"],
  },
  {
    slug: "feature-145",
    title: "任意時間のKW順位測定",
    category: "ランキング・順位追跡",
    description: "定期計測とは別に、任意のタイミングで即時に順位を計測。スポットチェック用。",
    demoType: "api",
    details: "定期バッチとは別に、管理画面からワンクリックで即時の順位計測を実行。クライアントへの報告前や施策実施直後のスポットチェックに最適です。",
    icon: "⏱️",
    status: "active",
    techStack: ["Google Maps API", "即時計測", "オンデマンド実行"],
  },

  // ============================================================
  // ユーザー・権限管理 (user-management)
  // ============================================================
  {
    slug: "feature-146",
    title: "Admin/Agent/Owner/Shop 階層管理",
    category: "ユーザー・権限管理",
    description: "管理者→代理店→オーナー→店舗の4階層ユーザーロール管理。権限別アクセス制御。",
    demoType: "auth",
    details: "Admin（システム管理者）、Agent（代理店）、Owner（オーナー）、Shop（店舗スタッフ）の4階層でユーザーを管理。各階層に応じたメニュー表示・データアクセス制御を行います。",
    icon: "👥",
    status: "active",
    techStack: ["Supabase Auth", "JWT", "RBAC", "権限マトリクス"],
  },
  {
    slug: "feature-147",
    title: "管理者(Admin)管理",
    category: "ユーザー・権限管理",
    description: "システム管理者の作成・編集・削除。全機能へのフルアクセス権限。",
    demoType: "auth",
    details: "システム全体を管理するAdmin権限ユーザーのCRUD。全店舗・全代理店・全オーナーのデータにアクセス可能な最上位権限です。",
    icon: "🔐",
    status: "active",
    techStack: ["Supabase Auth", "ユーザー管理API", "権限制御"],
  },
  {
    slug: "feature-148",
    title: "代理店(Agent)管理",
    category: "ユーザー・権限管理",
    description: "代理店アカウントの作成・編集。配下のオーナー・店舗を管理する権限を付与。",
    demoType: "auth",
    details: "代理店ごとにアカウントを作成し、担当するオーナー・店舗へのアクセス権限を管理。代理店切り替え機能で複数代理店の横断管理も可能です。",
    icon: "🏢",
    status: "active",
    techStack: ["マルチテナント", "代理店スコープ", "権限管理"],
  },
  {
    slug: "feature-149",
    title: "オーナー(Owner)管理",
    category: "ユーザー・権限管理",
    description: "オーナーアカウントの作成・編集。配下の店舗グループを管理。",
    demoType: "auth",
    details: "オーナー（法人・個人事業主）のアカウント管理。配下の店舗をグループ化し、一括操作やグループ別レポートを提供します。",
    icon: "👤",
    status: "active",
    techStack: ["アカウント管理", "店舗グループ", "GORM"],
  },
  {
    slug: "feature-150",
    title: "店舗スタッフ(Shop)管理",
    category: "ユーザー・権限管理",
    description: "店舗単位のスタッフアカウント管理。自店舗のデータのみアクセス可能。",
    demoType: "auth",
    details: "店舗スタッフは自店舗のGBP情報・口コミ・投稿・パフォーマンスのみ閲覧・操作可能。他店舗のデータは一切見えないスコープ制御を実装。",
    icon: "🏪",
    status: "active",
    techStack: ["スコープ制御", "店舗単位認証", "データフィルタ"],
  },
  {
    slug: "feature-151",
    title: "Google OAuth連携・GBPアカウント紐付け",
    category: "ユーザー・権限管理",
    description: "Google OAuthでGBPアカウントを認証し、システムの店舗と自動紐付け。",
    demoType: "auth",
    details: "Google OAuth 2.0認証フローでGBPアカウントにアクセス。Account Management APIで保有ロケーション一覧を取得し、システム上の店舗と紐付けます。招待管理にも対応。",
    icon: "🔗",
    status: "active",
    techStack: ["Google OAuth 2.0", "GBP Account Management API", "招待管理"],
  },
  {
    slug: "feature-152",
    title: "パスワードリセット",
    category: "ユーザー・権限管理",
    description: "ユーザーのパスワードリセット機能。メール送信でセキュアにリセット。",
    demoType: "auth",
    details: "Supabase Authのパスワードリセット機能を活用。リセットメール送信→新パスワード設定のフローをセキュアに提供します。",
    icon: "🔑",
    status: "active",
    techStack: ["Supabase Auth", "メール送信", "セキュリティ"],
  },
  {
    slug: "feature-153",
    title: "監査ログ",
    category: "ユーザー・権限管理",
    description: "誰がいつ何を変更したかの全操作ログを記録。コンプライアンス対応。",
    demoType: "monitor",
    details: "全ユーザーの操作（ログイン・データ変更・設定変更・API呼び出し等）をタイムスタンプ付きで記録。不正操作の検知やコンプライアンス対応に活用します。",
    icon: "📋",
    status: "active",
    techStack: ["監査ログDB", "操作記録", "検索・フィルタ"],
  },

  // ============================================================
  // 店舗管理 (shop-management)
  // ============================================================
  {
    slug: "feature-154",
    title: "店舗の登録・編集・削除",
    category: "店舗管理",
    description: "店舗情報のCRUD操作。GBPロケーションとの紐付け、優先度設定も管理。",
    demoType: "settings",
    details: "店舗の新規登録・情報編集・削除（論理削除）を管理画面から操作。GBPロケーションとの紐付けや表示優先度の設定もここで行います。",
    icon: "🏠",
    status: "active",
    techStack: ["CRUD API", "GBP紐付け", "優先度管理"],
  },
  {
    slug: "feature-155",
    title: "店舗グループ管理",
    category: "店舗管理",
    description: "系列店・エリア別など任意のグループで店舗を分類。グループ単位での一括操作に対応。",
    demoType: "settings",
    details: "店舗をブランド別・エリア別・業種別など任意のグループに分類。グループ単位での一括投稿・レポート生成・パフォーマンス比較が可能です。",
    icon: "📂",
    status: "active",
    techStack: ["グループ管理", "一括操作", "フィルタリング"],
  },
  {
    slug: "feature-156",
    title: "GBPアカウント・ロケーション関連付け",
    category: "店舗管理",
    description: "GoogleアカウントとGBPロケーションをシステム上の店舗に関連付け。複数アカウント対応。",
    demoType: "api",
    details: "Account Management APIで管理下のGBPアカウント一覧を取得し、Business Information APIでロケーション詳細を取得。システム上の店舗と紐付けて管理します。",
    icon: "🔗",
    status: "active",
    techStack: ["GBP Account Management API", "Business Information API", "関連付け管理"],
  },
  {
    slug: "feature-157",
    title: "店舗ダッシュボード",
    category: "店舗管理",
    description: "店舗ごとのKPI一覧画面。口コミ数・評価・順位・インサイト・投稿状況を一画面で把握。",
    demoType: "analytics",
    details: "個別店舗の全KPIを1つのダッシュボードに集約。口コミ数・平均評価・検索順位・インサイト推移・投稿状況・パフォーマンスをリアルタイムで表示します。",
    icon: "📊",
    status: "active",
    techStack: ["KPIダッシュボード", "リアルタイムデータ", "Recharts"],
  },
  {
    slug: "feature-158",
    title: "全店舗一覧・検索・フィルタ",
    category: "店舗管理",
    description: "500+店舗を業種・エリア・ステータス・担当者・サービス種別で絞り込み検索。",
    demoType: "settings",
    details: "全店舗をテーブル形式で一覧表示。業種・エリア・契約ステータス・担当者・契約サービス（MEO/広告/両方）での絞り込み・ソート・検索に対応します。",
    icon: "🔍",
    status: "active",
    techStack: ["データテーブル", "フィルタリング", "ページネーション"],
  },
  {
    slug: "feature-159",
    title: "店舗切り替え（代理店/オーナー切り替え含む）",
    category: "店舗管理",
    description: "サイドバーから代理店→オーナー→店舗をドリルダウンで切り替え。コンボボックス検索対応。",
    demoType: "settings",
    details: "サイドバーのコンボボックスで代理店→オーナー→店舗を階層的に切り替え。検索可能なセレクトボックスで500+店舗から素早く選択できます。",
    icon: "🔄",
    status: "active",
    techStack: ["Combobox UI", "階層フィルタ", "Zustand"],
  },

  // ============================================================
  // レポート・PDF (reports)
  // ============================================================
  {
    slug: "feature-160",
    title: "パフォーマンスレポートPDF生成",
    category: "レポート・PDF",
    description: "月次パフォーマンスデータをPDF形式で自動生成。クライアントへの報告書として利用。",
    demoType: "analytics",
    details: "検索表示回数・クリック数・電話発信数・ルート検索数などのGBPパフォーマンスデータを集計し、グラフ付きのPDFレポートを自動生成。クライアントへの月次報告に使用します。",
    icon: "📄",
    status: "active",
    techStack: ["jsPDF", "html2canvas", "GBP Performance API"],
  },
  {
    slug: "feature-161",
    title: "ランキングレポートPDF生成",
    category: "レポート・PDF",
    description: "検索順位の推移をグラフ・テーブルでまとめたPDFレポートを自動生成。",
    demoType: "analytics",
    details: "対策キーワード別の順位推移・目標達成状況・競合比較をグラフとテーブルでまとめたPDFレポートを自動生成します。",
    icon: "📊",
    status: "active",
    techStack: ["jsPDF", "Recharts", "ランキングデータ"],
  },
  {
    slug: "feature-162",
    title: "売上レポートPDF生成",
    category: "レポート・PDF",
    description: "売上予測・ROI分析を含む総合レポートをPDF形式で出力。",
    demoType: "analytics",
    details: "売上予測データ・広告ROI・MEO経由のコンバージョン推計を統合した総合レポートをPDF出力。経営判断に必要なデータを1枚にまとめます。",
    icon: "💰",
    status: "active",
    techStack: ["jsPDF", "売上分析", "ROI計算"],
  },
  {
    slug: "feature-163",
    title: "エリア別パフォーマンス",
    category: "レポート・PDF",
    description: "複数店舗のパフォーマンスをエリア単位で集計・比較。全店舗横断レポート。",
    demoType: "analytics",
    details: "複数店舗のGBPパフォーマンスをエリア（都道府県・市区町村・商圏）単位で集計。エリア間の比較や全店舗の横断的なパフォーマンス分析を提供します。",
    icon: "🗾",
    status: "active",
    techStack: ["エリア集計", "全店舗横断分析", "比較ダッシュボード"],
  },
  {
    slug: "feature-164",
    title: "売上予測・シミュレーション",
    category: "レポート・PDF",
    description: "GBPインサイトと広告データから売上を予測。目標設定と実績の差分を可視化。",
    demoType: "analytics",
    details: "GBPのインサイトデータ（表示回数・クリック数・電話発信数等）と広告パフォーマンスを元に、AIが売上を予測。目標値と実績の差分をグラフで可視化します。",
    icon: "🔮",
    status: "active",
    techStack: ["予測AI", "回帰分析", "目標管理"],
  },
  {
    slug: "feature-165",
    title: "顧客専用ダッシュボード",
    category: "レポート・PDF",
    description: "クライアント（オーナー）が直接ログインして自店舗の状況を確認できるダッシュボード。",
    demoType: "analytics",
    details: "クライアント（オーナー/店舗スタッフ）が直接ログインし、自店舗のパフォーマンス・口コミ・投稿状況・順位をリアルタイムで確認できるダッシュボード。月次レポートの不要化を実現します。",
    icon: "👁️",
    status: "active",
    techStack: ["権限制御", "リアルタイムデータ", "レスポンシブUI"],
  },
  {
    slug: "feature-166",
    title: "レポート自動メール配信",
    category: "レポート・PDF",
    description: "月次レポートをPDF添付で自動メール配信。配信日・宛先を店舗ごとに設定。",
    demoType: "publish",
    details: "生成したPDFレポートを設定した配信日に自動でメール送信。店舗ごとに配信日・宛先・レポート種類を設定できます。",
    icon: "📬",
    status: "active",
    techStack: ["Resend / SendGrid", "Cronスケジューラ", "PDF添付"],
  },

  // ============================================================
  // 店舗診断・初期整備 (diagnosis-setup)
  // ============================================================
  {
    slug: "feature-167",
    title: "MEOスコア診断（12項目）",
    category: "店舗診断・初期整備",
    description: "GBP情報の充実度を12項目でスコアリング。改善すべきポイントを優先度付きで提示。",
    demoType: "analytics",
    details: "店舗名・カテゴリ・住所・電話・営業時間・写真数・口コミ数・口コミ評価・投稿頻度・属性充実度・説明文・Q&Aの12項目でMEOスコアを算出。改善優先度を提示します。",
    icon: "🩺",
    status: "active",
    techStack: ["スコアリングエンジン", "GBP API", "レーダーチャート"],
  },
  {
    slug: "feature-168",
    title: "プロフィール初期整備",
    category: "店舗診断・初期整備",
    description: "新規契約店舗のGBPプロフィールをベストプラクティスに沿って一括整備。",
    demoType: "settings",
    details: "新規契約時に店舗のGBPプロフィールを網羅的に整備。カテゴリ設定・営業時間・属性・説明文・写真・メニュー・Q&Aをチェックリスト形式で漏れなく設定します。",
    icon: "✅",
    status: "active",
    techStack: ["チェックリストUI", "GBP API", "一括設定"],
  },
  {
    slug: "feature-169",
    title: "対策キーワード設定（検索ボリューム付き）",
    category: "店舗診断・初期整備",
    description: "業種×エリアで対策キーワードを提案。月間検索ボリューム・競合度も表示。",
    demoType: "ai",
    details: "店舗の業種とエリアに基づいて対策キーワード候補を自動提案。各キーワードの月間検索ボリュームと競合度を表示し、優先順位を決定できます。",
    icon: "🔑",
    status: "active",
    techStack: ["キーワードプランナー", "Google Ads API", "AI提案"],
  },
  {
    slug: "feature-170",
    title: "説明文AI生成",
    category: "店舗診断・初期整備",
    description: "対策キーワードを自然に含んだGBP説明文をAIが自動生成。750文字以内で最適化。",
    demoType: "ai",
    details: "店舗の基本情報・対策キーワード・業種特性を考慮し、GBPの説明文をAIが自動生成。Googleのガイドラインに準拠した750文字以内の最適な説明文を作成します。",
    icon: "📝",
    status: "active",
    techStack: ["GPT-4", "キーワード最適化", "文字数制御"],
  },
  {
    slug: "feature-171",
    title: "反映前情報の自動保存（バックアップ）",
    category: "店舗診断・初期整備",
    description: "初期整備・変更前のGBP情報を自動バックアップ。解約時の復元にも対応。",
    demoType: "api",
    details: "GBP情報を変更する前に、現在の状態を自動でスナップショット保存。解約時に契約前の状態に復元する際のデータソースとしても活用します。GBP-backupツールと連携。",
    icon: "💾",
    status: "active",
    techStack: ["GBP API", "スナップショット", "GBP-backup連携"],
  },
  {
    slug: "feature-172",
    title: "ROI自動算出",
    category: "店舗診断・初期整備",
    description: "MEO対策費用に対する効果（表示回数・アクション数増加）をROIとして自動計算。",
    demoType: "analytics",
    details: "MEO対策の月額費用に対して、GBPインサイトの向上（表示回数・クリック数・電話発信数・ルート検索数）をROIとして自動算出。クライアントへの価値証明に活用します。",
    icon: "💹",
    status: "active",
    techStack: ["ROI計算エンジン", "GBP Insights", "コスト管理"],
  },
  {
    slug: "feature-173",
    title: "業界平均ベンチマーク",
    category: "店舗診断・初期整備",
    description: "同業種・同エリアの平均値と比較し、自店舗のポジションを客観的に把握。",
    demoType: "analytics",
    details: "Chubbyプラットフォーム内の同業種店舗データを集計し、業界平均のベンチマークを算出。自店舗のスコアと比較して強み・弱みを客観的に可視化します。",
    icon: "📊",
    status: "active",
    techStack: ["ベンチマークDB", "業種別集計", "比較チャート"],
  },

  // ============================================================
  // AIO・LLMO対策 (aio)
  // ============================================================
  {
    slug: "feature-174",
    title: "AI Overview表示回数トラッキング",
    category: "AIO・LLMO対策",
    description: "Google検索のAI Overview（AIによる概要）に自店舗が表示された回数を追跡。",
    demoType: "analytics",
    details: "Google Search Console APIやカスタム計測で、AI Overview（旧SGE）に自店舗情報が引用・表示された回数をトラッキング。AIO対策の効果測定に活用します。",
    icon: "🤖",
    status: "active",
    techStack: ["GSC API", "AIOトラッキング", "カスタム計測"],
  },
  {
    slug: "feature-175",
    title: "AIプラットフォーム別 表示/クリック分析",
    category: "AIO・LLMO対策",
    description: "ChatGPT/Gemini/Perplexity等のAIプラットフォーム別に表示・クリックを分析。",
    demoType: "analytics",
    details: "各AIプラットフォーム（Google AIO、ChatGPT、Gemini、Perplexity等）からの参照・表示・クリックを個別にトラッキングし、検索ワード別にテーブル表示します。",
    icon: "📊",
    status: "beta",
    techStack: ["リファラー分析", "AIプラットフォーム判定", "検索ワード解析"],
  },
  {
    slug: "feature-176",
    title: "Q&A管理・最適化",
    category: "AIO・LLMO対策",
    description: "GBPのQ&Aを管理し、AIが引用しやすい構造化された回答を自動生成。",
    demoType: "ai",
    details: "GBPのQ&Aセクションを一元管理。対策キーワードを含み、AIが引用しやすい構造化された回答をAIが自動生成します。未回答の質問の検知・通知にも対応。",
    icon: "❓",
    status: "active",
    techStack: ["GBP Q&A API", "構造化回答生成", "AI最適化"],
  },
  {
    slug: "feature-177",
    title: "構造化データ管理",
    category: "AIO・LLMO対策",
    description: "Schema.org準拠の構造化データ（LocalBusiness等）の生成・管理・検証。",
    demoType: "api",
    details: "店舗情報からSchema.org準拠の構造化データ（LocalBusiness、Restaurant等）を自動生成。JSON-LD形式で出力し、バリデーションツールで検証します。",
    icon: "📋",
    status: "active",
    techStack: ["Schema.org", "JSON-LD", "構造化データバリデーター"],
  },

  // ============================================================
  // バッチ・自動処理 (batch)
  // ============================================================
  {
    slug: "feature-178",
    title: "バッチジョブ管理・監視",
    category: "バッチ・自動処理",
    description: "定期バッチ（順位計測/パフォーマンス取得/投稿予約/レビュー返信）の実行状況を一元監視。",
    demoType: "monitor",
    details: "全バッチジョブ（ランキング検索・パフォーマンス取得・投稿予約実行・レビュー自動返信・ヘルスチェック）の実行履歴・成功/失敗・処理時間を一元管理します。",
    icon: "⚙️",
    status: "active",
    techStack: ["Cobra CLI", "Cron", "実行ログDB", "CloudWatch"],
  },
  {
    slug: "feature-179",
    title: "パフォーマンスデータ自動取得",
    category: "バッチ・自動処理",
    description: "全店舗のGBPパフォーマンスデータを日次バッチで自動取得・蓄積。",
    demoType: "api",
    details: "GBP Performance APIを使って全店舗のインサイトデータ（表示回数・クリック数・電話発信・ルート検索等）を日次バッチで自動取得。過去18ヶ月分を蓄積します。",
    icon: "📥",
    status: "active",
    techStack: ["GBP Performance API", "バッチ処理", "データパイプライン"],
  },
  {
    slug: "feature-180",
    title: "ヘルスチェック",
    category: "バッチ・自動処理",
    description: "システム全体の稼働確認。DB接続・外部API疎通・バッチ実行状況を定期チェック。",
    demoType: "monitor",
    details: "データベース接続・外部API（GBP/Google Ads/Meta等）の疎通確認・バッチジョブの実行状況を定期的にチェック。異常検知時にアラートを発信します。",
    icon: "💚",
    status: "active",
    techStack: ["ヘルスチェックAPI", "死活監視", "CloudWatch"],
  },
  {
    slug: "feature-181",
    title: "レート制限管理",
    category: "バッチ・自動処理",
    description: "Google API等のレート制限を管理し、429エラーを防止。リトライ・キュー制御。",
    demoType: "settings",
    details: "各外部APIのレート制限（QPM/QPD）を管理し、制限を超えないようリクエストをキュー制御。429エラー発生時の自動リトライも行います。",
    icon: "🚦",
    status: "active",
    techStack: ["レートリミッター", "キューイング", "リトライ制御"],
  },

  // ============================================================
  // 顧客マスタ連携 (customer-master)
  // ============================================================
  {
    slug: "feature-182",
    title: "顧客マスタ（shop_id統合管理）",
    category: "顧客マスタ連携",
    description: "全システム共通のshop_idで500+店舗を統合管理。店舗名変更は1箇所で全連携。",
    demoType: "settings",
    details: "代理店→顧客→店舗→サービスの4階層で全顧客データを管理。shop_idを全システム共通キーとし、店舗名変更時はマスタ1箇所を変更するだけで100+スプレッドシートに自動反映します。",
    icon: "🗂️",
    status: "active",
    techStack: ["Google Sheets API", "マスタ管理", "一括同期"],
  },
  {
    slug: "feature-183",
    title: "スプレッドシート一括更新（Sheets API）",
    category: "顧客マスタ連携",
    description: "マスタデータ変更時に100+スプレッドシートをSheets APIで一括自動更新。",
    demoType: "api",
    details: "顧客マスタの変更（店舗名・住所・電話・担当者等）を検知し、Google Sheets APIで全連携スプレッドシートを一括自動更新。手動修正ゼロを実現します。",
    icon: "📊",
    status: "active",
    techStack: ["Google Sheets API v4", "バッチ更新", "変更検知"],
  },
  {
    slug: "feature-184",
    title: "解約時自動バックアップ・復元",
    category: "顧客マスタ連携",
    description: "マスタで解約ステータスに変更→GBP情報を自動バックアップ→契約前の状態に復元。",
    demoType: "api",
    details: "顧客マスタのステータスをchurnedに変更すると、GBP-backupツールが自動起動。現在のGBP情報をバックアップした後、契約前のスナップショットに復元します。",
    icon: "🔄",
    status: "active",
    techStack: ["GBP-backup連携", "自動トリガー", "スナップショット復元"],
  },
  {
    slug: "feature-185",
    title: "解約予兆スコア",
    category: "顧客マスタ連携",
    description: "LINE返信頻度・口コミ率・レポート閲覧・素材提供状況から解約リスクをAIが予測。",
    demoType: "ai",
    details: "複数のデータソース（LINE返信頻度、口コミ返信率の低下、レポート未閲覧、投稿素材の未提供、支払い遅延等）からAIが解約リスクを予測。HIGH/MEDIUM/LOWでスコアリングし、早期対応を促します。",
    icon: "⚠️",
    status: "beta",
    techStack: ["予測AI", "多変量分析", "リスクスコアリング"],
  },
  {
    slug: "feature-186",
    title: "引き継ぎ情報自動生成",
    category: "顧客マスタ連携",
    description: "担当変更時に全データ（契約・対応履歴・店主の性格・注意点）から引き継ぎ資料を自動生成。",
    demoType: "ai",
    details: "顧客マスタ・Slack会話履歴・LINE会話履歴・口コミ対応履歴・投稿履歴・GBPデータを統合し、担当引き継ぎに必要な全情報をAIが自動でまとめます。",
    icon: "📋",
    status: "beta",
    techStack: ["RAG", "Dify連携", "全データ統合"],
  },

  // ============================================================
  // AI社長・AI課長連携 (ai-integration)
  // ============================================================
  {
    slug: "feature-187",
    title: "AI社長（Slack Bot）",
    category: "AI社長・AI課長連携",
    description: "Dify RAGベースのAI社長。社内の全データを学習し、社員の質問に即座に回答。",
    demoType: "ai",
    details: "Dify上のベクトルDB（社内マニュアル・スプレッドシート・会議録・Slack会話・LINE会話）を検索し、Claude Opusが社長として回答。社長の訂正も自動学習します。",
    icon: "🤖",
    status: "active",
    techStack: ["Dify", "Claude Opus", "Slack Bolt", "RAG", "ベクトルDB"],
  },
  {
    slug: "feature-188",
    title: "AI課長（LINE Bot ROM監視）",
    category: "AI社長・AI課長連携",
    description: "100+のLINEグループを常時ROM監視。発言せずにクライアントの会話を全て把握・蓄積。",
    demoType: "monitor",
    details: "LINE Messaging API Webhookで100+のLINEグループの発言を常時受信。グループ内では一切発言せず、全会話をDifyナレッジに蓄積し、Slackに自動転送します。",
    icon: "👁️",
    status: "active",
    techStack: ["LINE Messaging API", "Webhook", "Dify連携", "Slack転送"],
  },
  {
    slug: "feature-189",
    title: "LINE発言→自動タスク生成・追跡",
    category: "AI社長・AI課長連携",
    description: "LINEでの「休業」「メニュー変更」「店名変更」等を検知し、自動でタスク化。完了まで追跡。",
    demoType: "ai",
    details: "AI課長がLINEの会話からアクション必要なキーワードを検知し、自動でタスクを生成。GBP更新・NAP修正・Dropbox対応などのタスクを担当者にアサインし、完了するまでSlackでリマインドします。",
    icon: "📋",
    status: "active",
    techStack: ["NLP", "タスク管理", "自動リマインド", "Slack通知"],
  },
  {
    slug: "feature-190",
    title: "重要キーワード検知・緊急アラート",
    category: "AI社長・AI課長連携",
    description: "LINEグループで「クレーム」「解約」「怒り」等を検知し、Slackに緊急アラート。",
    demoType: "monitor",
    details: "AI課長がLINE上のクレーム・解約示唆・不満表明などの重要キーワードを検知し、即時にSlackの指定チャンネルに緊急アラートを発信。迅速な対応を促します。",
    icon: "🚨",
    status: "active",
    techStack: ["キーワード検知", "感情分析", "緊急通知"],
  },
];

export function getFeatureBySlug(slug: string): FeatureDetail | undefined {
  return featureDetails.find((f) => f.slug === slug);
}

export function getAllSlugs(): string[] {
  return featureDetails.map((f) => f.slug);
}
