-- 計測地点の距離を全店舗500mに揃える
--
-- 【結論: 2026-08-01 時点では実行不要だった】
-- 実行前に分布を確認したところ、608店舗すべてが grid_interval_m = NULL
-- （＝明示設定なし・既定値を使用）だった。
--
--   SELECT COALESCE(grid_interval_m, 0) AS interval_m, COUNT(*)
--     FROM shops GROUP BY 1 ORDER BY 1;
--   → interval_m = 0 / count = 608
--
-- したがってコード側の既定値変更（DEFAULT_INTERVAL 1000 → 500）だけで
-- 全店舗に反映され、このUPDATEは不要。
--
-- 【将来、既定値を変えたくなったとき】
-- 画面から距離を保存した店舗には明示値が入るため、そのときは
-- 下のUPDATEで既定値へ戻す。ただし郊外店など意図的に広げた設定も
-- 消えるので、必ず上の分布確認をしてから実行すること。
--
-- 明示的に数値を入れずNULLに戻すのは、今後さらに既定値を変えたときに
-- 全店舗が自動で追随できるようにするため。

-- UPDATE shops
--    SET grid_interval_m = NULL
--  WHERE grid_interval_m IS NOT NULL;
